/********************************************************************************
** Form generated from reading UI file 'dialog.ui'
**
** Created by: Qt User Interface Compiler version 5.0.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOG_H
#define UI_DIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QPushButton *b00;
    QPushButton *b01;
    QPushButton *b02;
    QPushButton *b03;
    QPushButton *b04;
    QPushButton *b10;
    QPushButton *b11;
    QPushButton *b12;
    QPushButton *b13;
    QPushButton *b14;
    QPushButton *b20;
    QPushButton *b21;
    QPushButton *b22;
    QPushButton *b23;
    QPushButton *b24;
    QPushButton *b50;
    QPushButton *b43;
    QPushButton *b34;
    QPushButton *b52;
    QPushButton *b53;
    QPushButton *b54;
    QPushButton *b42;
    QPushButton *b30;
    QPushButton *b32;
    QPushButton *b40;
    QPushButton *b31;
    QPushButton *b33;
    QPushButton *b41;
    QPushButton *b51;
    QPushButton *b44;
    QPushButton *m11;
    QPushButton *m10;
    QPushButton *m9;
    QPushButton *m8;
    QPushButton *m7;
    QPushButton *m6;
    QPushButton *m5;
    QPushButton *m4;
    QPushButton *m3;
    QPushButton *m2;
    QPushButton *m1;
    QPushButton *descarte;
    QPushButton *m12;
    QPushButton *m21;
    QPushButton *m15;
    QPushButton *m13;
    QPushButton *m19;
    QPushButton *m17;
    QPushButton *m18;
    QPushButton *m20;
    QPushButton *m14;
    QPushButton *m16;
    QPushButton *leave;
    QPushButton *m22;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QStringLiteral("Dialog"));
        Dialog->setWindowModality(Qt::ApplicationModal);
        Dialog->resize(743, 452);
        QSizePolicy sizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::MinimumExpanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Dialog->sizePolicy().hasHeightForWidth());
        Dialog->setSizePolicy(sizePolicy);
        Dialog->setMinimumSize(QSize(743, 452));
        Dialog->setMaximumSize(QSize(743, 452));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        QBrush brush2(QColor(127, 127, 127, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush2);
        QBrush brush3(QColor(170, 170, 170, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush4(QColor(255, 255, 220, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        Dialog->setPalette(palette);
        Dialog->setStyleSheet(QLatin1String("QDialog {background-image: url(./img/fondo.jpg) }\n"
"QMessageBox{background-image: url(./img/53.png)}\n"
""));
        b00 = new QPushButton(Dialog);
        b00->setObjectName(QStringLiteral("b00"));
        b00->setEnabled(false);
        b00->setGeometry(QRect(25, 20, 100, 125));
        b00->setFlat(true);
        b01 = new QPushButton(Dialog);
        b01->setObjectName(QStringLiteral("b01"));
        b01->setEnabled(false);
        b01->setGeometry(QRect(25, 45, 100, 125));
        b01->setFlat(true);
        b02 = new QPushButton(Dialog);
        b02->setObjectName(QStringLiteral("b02"));
        b02->setEnabled(false);
        b02->setGeometry(QRect(25, 70, 100, 125));
        b02->setFlat(true);
        b03 = new QPushButton(Dialog);
        b03->setObjectName(QStringLiteral("b03"));
        b03->setEnabled(false);
        b03->setGeometry(QRect(25, 95, 100, 125));
        b03->setFlat(true);
        b04 = new QPushButton(Dialog);
        b04->setObjectName(QStringLiteral("b04"));
        b04->setGeometry(QRect(25, 120, 100, 125));
        b04->setFlat(true);
        b10 = new QPushButton(Dialog);
        b10->setObjectName(QStringLiteral("b10"));
        b10->setEnabled(false);
        b10->setGeometry(QRect(140, 20, 100, 125));
        b10->setFlat(true);
        b11 = new QPushButton(Dialog);
        b11->setObjectName(QStringLiteral("b11"));
        b11->setEnabled(false);
        b11->setGeometry(QRect(140, 45, 100, 125));
        b11->setFlat(true);
        b12 = new QPushButton(Dialog);
        b12->setObjectName(QStringLiteral("b12"));
        b12->setEnabled(false);
        b12->setGeometry(QRect(140, 70, 100, 125));
        b12->setFlat(true);
        b13 = new QPushButton(Dialog);
        b13->setObjectName(QStringLiteral("b13"));
        b13->setEnabled(false);
        b13->setGeometry(QRect(140, 95, 100, 125));
        b13->setFlat(true);
        b14 = new QPushButton(Dialog);
        b14->setObjectName(QStringLiteral("b14"));
        b14->setGeometry(QRect(140, 120, 100, 125));
        b14->setFlat(true);
        b20 = new QPushButton(Dialog);
        b20->setObjectName(QStringLiteral("b20"));
        b20->setEnabled(false);
        b20->setGeometry(QRect(255, 20, 100, 125));
        b20->setFlat(true);
        b21 = new QPushButton(Dialog);
        b21->setObjectName(QStringLiteral("b21"));
        b21->setEnabled(false);
        b21->setGeometry(QRect(255, 45, 100, 125));
        b21->setFlat(true);
        b22 = new QPushButton(Dialog);
        b22->setObjectName(QStringLiteral("b22"));
        b22->setEnabled(false);
        b22->setGeometry(QRect(255, 70, 100, 125));
        b22->setFlat(true);
        b23 = new QPushButton(Dialog);
        b23->setObjectName(QStringLiteral("b23"));
        b23->setEnabled(false);
        b23->setGeometry(QRect(255, 95, 100, 125));
        b23->setFlat(true);
        b24 = new QPushButton(Dialog);
        b24->setObjectName(QStringLiteral("b24"));
        b24->setGeometry(QRect(255, 120, 100, 125));
        b24->setFlat(true);
        b50 = new QPushButton(Dialog);
        b50->setObjectName(QStringLiteral("b50"));
        b50->setEnabled(false);
        b50->setGeometry(QRect(600, 20, 100, 125));
        b50->setFlat(true);
        b43 = new QPushButton(Dialog);
        b43->setObjectName(QStringLiteral("b43"));
        b43->setEnabled(false);
        b43->setGeometry(QRect(485, 95, 100, 125));
        b43->setFlat(true);
        b34 = new QPushButton(Dialog);
        b34->setObjectName(QStringLiteral("b34"));
        b34->setGeometry(QRect(370, 120, 100, 125));
        b34->setFlat(true);
        b52 = new QPushButton(Dialog);
        b52->setObjectName(QStringLiteral("b52"));
        b52->setEnabled(false);
        b52->setGeometry(QRect(600, 70, 100, 125));
        b52->setFlat(true);
        b53 = new QPushButton(Dialog);
        b53->setObjectName(QStringLiteral("b53"));
        b53->setEnabled(false);
        b53->setGeometry(QRect(600, 95, 100, 125));
        b53->setFlat(true);
        b54 = new QPushButton(Dialog);
        b54->setObjectName(QStringLiteral("b54"));
        b54->setGeometry(QRect(600, 120, 100, 125));
        b54->setFlat(true);
        b42 = new QPushButton(Dialog);
        b42->setObjectName(QStringLiteral("b42"));
        b42->setEnabled(false);
        b42->setGeometry(QRect(485, 70, 100, 125));
        b42->setFlat(true);
        b30 = new QPushButton(Dialog);
        b30->setObjectName(QStringLiteral("b30"));
        b30->setEnabled(false);
        b30->setGeometry(QRect(370, 20, 100, 125));
        b30->setFlat(true);
        b32 = new QPushButton(Dialog);
        b32->setObjectName(QStringLiteral("b32"));
        b32->setEnabled(false);
        b32->setGeometry(QRect(370, 70, 100, 125));
        b32->setFlat(true);
        b40 = new QPushButton(Dialog);
        b40->setObjectName(QStringLiteral("b40"));
        b40->setEnabled(false);
        b40->setGeometry(QRect(485, 20, 100, 125));
        b40->setFlat(true);
        b31 = new QPushButton(Dialog);
        b31->setObjectName(QStringLiteral("b31"));
        b31->setEnabled(false);
        b31->setGeometry(QRect(370, 45, 100, 125));
        b31->setFlat(true);
        b33 = new QPushButton(Dialog);
        b33->setObjectName(QStringLiteral("b33"));
        b33->setEnabled(false);
        b33->setGeometry(QRect(370, 95, 100, 125));
        b33->setFlat(true);
        b41 = new QPushButton(Dialog);
        b41->setObjectName(QStringLiteral("b41"));
        b41->setEnabled(false);
        b41->setGeometry(QRect(485, 45, 100, 125));
        b41->setFlat(true);
        b51 = new QPushButton(Dialog);
        b51->setObjectName(QStringLiteral("b51"));
        b51->setEnabled(false);
        b51->setGeometry(QRect(600, 45, 100, 125));
        b51->setFlat(true);
        b44 = new QPushButton(Dialog);
        b44->setObjectName(QStringLiteral("b44"));
        b44->setGeometry(QRect(485, 120, 100, 125));
        b44->setFlat(true);
        m11 = new QPushButton(Dialog);
        m11->setObjectName(QStringLiteral("m11"));
        m11->setEnabled(false);
        m11->setGeometry(QRect(250, 280, 100, 125));
        m11->setFlat(true);
        m10 = new QPushButton(Dialog);
        m10->setObjectName(QStringLiteral("m10"));
        m10->setEnabled(false);
        m10->setGeometry(QRect(270, 280, 100, 125));
        m10->setFlat(true);
        m9 = new QPushButton(Dialog);
        m9->setObjectName(QStringLiteral("m9"));
        m9->setEnabled(false);
        m9->setGeometry(QRect(290, 280, 100, 125));
        m9->setFlat(true);
        m8 = new QPushButton(Dialog);
        m8->setObjectName(QStringLiteral("m8"));
        m8->setEnabled(false);
        m8->setGeometry(QRect(310, 280, 100, 125));
        m8->setFlat(true);
        m7 = new QPushButton(Dialog);
        m7->setObjectName(QStringLiteral("m7"));
        m7->setEnabled(false);
        m7->setGeometry(QRect(330, 280, 100, 125));
        m7->setFlat(true);
        m6 = new QPushButton(Dialog);
        m6->setObjectName(QStringLiteral("m6"));
        m6->setEnabled(false);
        m6->setGeometry(QRect(350, 280, 100, 125));
        m6->setFlat(true);
        m5 = new QPushButton(Dialog);
        m5->setObjectName(QStringLiteral("m5"));
        m5->setEnabled(false);
        m5->setGeometry(QRect(370, 280, 100, 125));
        m5->setFlat(true);
        m4 = new QPushButton(Dialog);
        m4->setObjectName(QStringLiteral("m4"));
        m4->setEnabled(false);
        m4->setGeometry(QRect(390, 280, 100, 125));
        m4->setFlat(true);
        m3 = new QPushButton(Dialog);
        m3->setObjectName(QStringLiteral("m3"));
        m3->setEnabled(false);
        m3->setGeometry(QRect(410, 280, 100, 125));
        m3->setFlat(true);
        m2 = new QPushButton(Dialog);
        m2->setObjectName(QStringLiteral("m2"));
        m2->setEnabled(false);
        m2->setGeometry(QRect(430, 280, 100, 125));
        m2->setFlat(true);
        m1 = new QPushButton(Dialog);
        m1->setObjectName(QStringLiteral("m1"));
        m1->setGeometry(QRect(450, 280, 100, 125));
        m1->setFlat(true);
        descarte = new QPushButton(Dialog);
        descarte->setObjectName(QStringLiteral("descarte"));
        descarte->setEnabled(true);
        descarte->setGeometry(QRect(600, 280, 100, 125));
        descarte->setFlat(true);
        m12 = new QPushButton(Dialog);
        m12->setObjectName(QStringLiteral("m12"));
        m12->setEnabled(false);
        m12->setGeometry(QRect(230, 280, 100, 125));
        m12->setFlat(true);
        m21 = new QPushButton(Dialog);
        m21->setObjectName(QStringLiteral("m21"));
        m21->setEnabled(false);
        m21->setGeometry(QRect(50, 280, 100, 125));
        m21->setFlat(true);
        m15 = new QPushButton(Dialog);
        m15->setObjectName(QStringLiteral("m15"));
        m15->setEnabled(false);
        m15->setGeometry(QRect(170, 280, 100, 125));
        m15->setFlat(true);
        m13 = new QPushButton(Dialog);
        m13->setObjectName(QStringLiteral("m13"));
        m13->setEnabled(false);
        m13->setGeometry(QRect(210, 280, 100, 125));
        m13->setFlat(true);
        m19 = new QPushButton(Dialog);
        m19->setObjectName(QStringLiteral("m19"));
        m19->setEnabled(false);
        m19->setGeometry(QRect(90, 280, 100, 125));
        m19->setFlat(true);
        m17 = new QPushButton(Dialog);
        m17->setObjectName(QStringLiteral("m17"));
        m17->setEnabled(false);
        m17->setGeometry(QRect(130, 280, 100, 125));
        m17->setFlat(true);
        m18 = new QPushButton(Dialog);
        m18->setObjectName(QStringLiteral("m18"));
        m18->setEnabled(false);
        m18->setGeometry(QRect(110, 280, 100, 125));
        m18->setFlat(true);
        m20 = new QPushButton(Dialog);
        m20->setObjectName(QStringLiteral("m20"));
        m20->setEnabled(false);
        m20->setGeometry(QRect(70, 280, 100, 125));
        m20->setFlat(true);
        m14 = new QPushButton(Dialog);
        m14->setObjectName(QStringLiteral("m14"));
        m14->setEnabled(false);
        m14->setGeometry(QRect(190, 280, 100, 125));
        m14->setFlat(true);
        m16 = new QPushButton(Dialog);
        m16->setObjectName(QStringLiteral("m16"));
        m16->setEnabled(false);
        m16->setGeometry(QRect(150, 280, 100, 125));
        m16->setFlat(true);
        leave = new QPushButton(Dialog);
        leave->setObjectName(QStringLiteral("leave"));
        leave->setGeometry(QRect(640, 410, 97, 31));
        leave->setFlat(false);
        m22 = new QPushButton(Dialog);
        m22->setObjectName(QStringLiteral("m22"));
        m22->setEnabled(false);
        m22->setGeometry(QRect(30, 280, 100, 125));
        m22->setFlat(true);
        m22->raise();
        m21->raise();
        m20->raise();
        m19->raise();
        m18->raise();
        m17->raise();
        m16->raise();
        m15->raise();
        m14->raise();
        m13->raise();
        m12->raise();
        b50->raise();
        b40->raise();
        b30->raise();
        b20->raise();
        b10->raise();
        b00->raise();
        b01->raise();
        b02->raise();
        b03->raise();
        b04->raise();
        b11->raise();
        b12->raise();
        b13->raise();
        b14->raise();
        b21->raise();
        b22->raise();
        b23->raise();
        b24->raise();
        b31->raise();
        b32->raise();
        b33->raise();
        b34->raise();
        b41->raise();
        b42->raise();
        b43->raise();
        b44->raise();
        b51->raise();
        b52->raise();
        b53->raise();
        b54->raise();
        m11->raise();
        m10->raise();
        m9->raise();
        m8->raise();
        m7->raise();
        m6->raise();
        m5->raise();
        m4->raise();
        m3->raise();
        m2->raise();
        m1->raise();
        descarte->raise();
        leave->raise();

        retranslateUi(Dialog);

        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "Solitario Golf ", 0));
        b00->setText(QString());
        b01->setText(QString());
        b02->setText(QString());
        b03->setText(QString());
        b04->setText(QString());
        b10->setText(QString());
        b11->setText(QString());
        b12->setText(QString());
        b13->setText(QString());
        b14->setText(QString());
        b20->setText(QString());
        b21->setText(QString());
        b22->setText(QString());
        b23->setText(QString());
        b24->setText(QString());
        b50->setText(QString());
        b43->setText(QString());
        b34->setText(QString());
        b52->setText(QString());
        b53->setText(QString());
        b54->setText(QString());
        b42->setText(QString());
        b30->setText(QString());
        b32->setText(QString());
        b40->setText(QString());
        b31->setText(QString());
        b33->setText(QString());
        b41->setText(QString());
        b51->setText(QString());
        b44->setText(QString());
        m11->setText(QString());
        m10->setText(QString());
        m9->setText(QString());
        m8->setText(QString());
        m7->setText(QString());
        m6->setText(QString());
        m5->setText(QString());
        m4->setText(QString());
        m3->setText(QString());
        m2->setText(QString());
        m1->setText(QString());
        descarte->setText(QString());
        m12->setText(QString());
        m21->setText(QString());
        m15->setText(QString());
        m13->setText(QString());
        m19->setText(QString());
        m17->setText(QString());
        m18->setText(QString());
        m20->setText(QString());
        m14->setText(QString());
        m16->setText(QString());
        leave->setText(QApplication::translate("Dialog", "Abandonar", 0));
        m22->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOG_H
